name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - dev

env:
  AZURE_WEBAPP_NAME: demo-test-webapp-dev
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore
        run: dotnet restore ./CurrentTimeService.sln
        
      - name: Build
        run: dotnet build ./CurrentTimeService.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./CurrentTimeService.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"\
        
          create_pr_job:
            runs-on: ubuntu-latest
            needs: publish  # This job runs after the publish job
            if: github.ref == 'refs/heads/dev'  # Ensure it only runs on dev branch
            name: Create Pull Request to QA
            steps:
              - name: Create Pull Request
                uses: peter-evans/create-pull-request@v5
                with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: "Merge dev into qa"
                  title: "Pull Request: Merge dev into qa"
                  body: "This PR merges the changes from dev into qa."
                  base: qa
                  head: dev
                  branch: dev-to-qa-automated-pr
